### ISSUE TITLE
Exclude mail

### ISSUE THREAD

**Issue by jcatello** [Hestat/blazescan#4]
Anyway to add an option to exclude the mail directory

**Comment by Hestat** [comment]
By default it should not scan mail directories, unless it is in the public_html dir of a cpanel server which is non standard. Or if the directory you give it to scan using the -d flag has the mail directory below it in the file structure, in that case you may want to specify a directory further down the directory tree. 

Let me know if this helps, or if not, provide an example of what you are seeing.

**Comment by jcatello** [comment]
cPanel gives you the option to no longer force having to add the addon / subdomain's in public_html, you can now freely add them right into the home directory so to ensure you are scanning all possible doc roots now you would want to scan /home/user/* which means it would include mail

> Restrict document roots to public_html [?]
This option mandates that document roots for all newly-created websites must reside under the document root for the account’s primary website. This option does not apply when you transfer or restore accounts.

**Comment by Hestat** [comment]
Ah, the scanner is setup to account for this, if you use the -a or -u flag it enumerates all cpanel doc roots, regardless of if they are in public_html or not.
