### ISSUE TITLE
Email Alerts & Account Suspension

### ISSUE THREAD

**Issue by kushalraha** [Hestat/blazescan#6]
How about adding the ability to suspend the infected account and sending an email with the results of the test?

**Comment by Hestat** [comment]
I will look into some options to allow for a mail to. As for account suspension, this is a little out of the scope of the project. you always can look into your own trigger for this with cpanel using the /scripts/suspendaccnt command.

**Comment by Hestat** [comment]
Mail feature added in 1.3 update @kushalraha 
[https://laskowski-tech.com/2018/07/21/blazescan-v-1-3-updates/](https://laskowski-tech.com/2018/07/21/blazescan-v-1-3-updates/)
