### ISSUE TITLE
error

### ISSUE THREAD

**Issue by techwithquestion** [Hestat/blazescan#7]
I am getting this error while scanning 
LibClamAV Error: Can't load /usr/local/scan/lw-yara/lw-rules_index.yar: Malformed database

how to fix this ?

**Comment by Hestat** [comment]
If you get that response then you have a version of clamscan installed which is older than version 98. You will need to uninstall your currently clamscan binary and install an up to date version.

Currently most disto package managers should be at version 99.4, or you can get version 100 directly from https://www.clamav.net/downloads
